location /api/auth {
    try_files $uri $uri/ /api/auth/index.php?$query_string;
}

location /api/payment {
    try_files $uri $uri/ /api/payment/index.php?$query_string;
}

location /api/apikey {
    try_files $uri $uri/ /api/apikey/index.php?$query_string;
}

location ~ ^/api/(auth|payment|apikey)/index\.php$ {
    fastcgi_pass unix:/tmp/php-cgi-82.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
}

location ~ ^/api/payment/notify\.php$ {
    fastcgi_pass unix:/tmp/php-cgi-82.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
}
